import { useState } from "react";
import { useNavigate } from "react-router";
import {
  FileText,
  Send,
  Save,
  AlertTriangle,
  Edit,
  Plus,
  Trash2,
  Search,
} from "lucide-react";

interface OrderItem {
  id: string;
  itemCode: string;
  itemName: string;
  category: string;
  currentStock: number;
  safetyStock: number;
  requestedQty: number;
  unit: string;
  reason: string;
}

interface AvailableItem {
  itemCode: string;
  itemName: string;
  category: string;
  currentStock: number;
  safetyStock: number;
  unit: string;
}

const mockAutoGeneratedItems: OrderItem[] = [
  {
    id: "1",
    itemCode: "MEAT-001",
    itemName: "소고기 패티",
    category: "육류",
    currentStock: 45,
    safetyStock: 50,
    requestedQty: 55,
    unit: "개",
    reason: "안전재고 미달 + 일평균 소비량 고려",
  },
  {
    id: "2",
    itemCode: "VEG-001",
    itemName: "감자",
    category: "채소",
    currentStock: 15,
    safetyStock: 50,
    requestedQty: 85,
    unit: "kg",
    reason: "안전재고 미달 (35kg 부족)",
  },
  {
    id: "3",
    itemCode: "DAIRY-001",
    itemName: "생크림",
    category: "유제품",
    currentStock: 12,
    safetyStock: 15,
    requestedQty: 18,
    unit: "L",
    reason: "안전재고 미달 + 유통기한 고려",
  },
  {
    id: "4",
    itemCode: "VEG-002",
    itemName: "양상추",
    category: "채소",
    currentStock: 8,
    safetyStock: 20,
    requestedQty: 27,
    unit: "kg",
    reason: "안전재고 미달 (12kg 부족)",
  },
];

// 전체 가용 품목 리스트 (안전 재고 충족 품목 포함)
const allAvailableItems: AvailableItem[] = [
  // 안전 재고 미달 품목
  {
    itemCode: "MEAT-001",
    itemName: "소고기 패티",
    category: "육류",
    currentStock: 45,
    safetyStock: 50,
    unit: "개",
  },
  {
    itemCode: "VEG-001",
    itemName: "감자",
    category: "채소",
    currentStock: 15,
    safetyStock: 50,
    unit: "kg",
  },
  {
    itemCode: "DAIRY-001",
    itemName: "생크림",
    category: "유제품",
    currentStock: 12,
    safetyStock: 15,
    unit: "L",
  },
  {
    itemCode: "VEG-002",
    itemName: "양상추",
    category: "채소",
    currentStock: 8,
    safetyStock: 20,
    unit: "kg",
  },
  // 안전 재고 충족 품목
  {
    itemCode: "BREAD-001",
    itemName: "버거빵",
    category: "빵류",
    currentStock: 180,
    safetyStock: 150,
    unit: "개",
  },
  {
    itemCode: "DAIRY-002",
    itemName: "체다치즈",
    category: "유제품",
    currentStock: 35,
    safetyStock: 25,
    unit: "장",
  },
  {
    itemCode: "SAUCE-001",
    itemName: "식용유",
    category: "소스류",
    currentStock: 20,
    safetyStock: 15,
    unit: "L",
  },
  {
    itemCode: "VEG-003",
    itemName: "토마토",
    category: "채소",
    currentStock: 18,
    safetyStock: 15,
    unit: "kg",
  },
  {
    itemCode: "VEG-004",
    itemName: "양파",
    category: "채소",
    currentStock: 25,
    safetyStock: 20,
    unit: "kg",
  },
  {
    itemCode: "SAUCE-002",
    itemName: "케챱",
    category: "소스류",
    currentStock: 12,
    safetyStock: 10,
    unit: "병",
  },
  {
    itemCode: "SAUCE-003",
    itemName: "머스타드",
    category: "소스류",
    currentStock: 10,
    safetyStock: 8,
    unit: "병",
  },
  {
    itemCode: "MEAT-002",
    itemName: "베이컨",
    category: "육류",
    currentStock: 22,
    safetyStock: 20,
    unit: "팩",
  },
];

export function OrderCreate() {
  const navigate = useNavigate();
  const [orderItems, setOrderItems] = useState<OrderItem[]>(
    mockAutoGeneratedItems
  );
  const [showSendModal, setShowSendModal] = useState(false);
  const [showAddItemModal, setShowAddItemModal] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");

  const updateQuantity = (id: string, newQty: number) => {
    setOrderItems(
      orderItems.map((item) =>
        item.id === id ? { ...item, requestedQty: newQty } : item
      )
    );
  };

  const updateReason = (id: string, newReason: string) => {
    setOrderItems(
      orderItems.map((item) =>
        item.id === id ? { ...item, reason: newReason } : item
      )
    );
  };

  const removeItem = (id: string) => {
    setOrderItems(orderItems.filter((item) => item.id !== id));
  };

  const addItem = (item: AvailableItem) => {
    // 이미 추가된 품목인지 확인
    if (orderItems.some((oi) => oi.itemCode === item.itemCode)) {
      alert("이미 발주 목록에 추가된 품목입니다.");
      return;
    }

    const newItem: OrderItem = {
      id: Date.now().toString(),
      itemCode: item.itemCode,
      itemName: item.itemName,
      category: item.category,
      currentStock: item.currentStock,
      safetyStock: item.safetyStock,
      requestedQty: item.safetyStock - item.currentStock > 0 
        ? item.safetyStock - item.currentStock + 10 
        : 10,
      unit: item.unit,
      reason: item.currentStock < item.safetyStock 
        ? "안전재고 미달" 
        : "추가 발주 요청",
    };

    setOrderItems([...orderItems, newItem]);
    setShowAddItemModal(false);
    setSearchTerm("");
  };

  const handleSaveDraft = () => {
    alert("발주서가 초안으로 저장되었습니다.");
    navigate("/orders/history");
  };

  const handleSend = () => {
    setShowSendModal(false);
    // Show toast message
    const toastEl = document.createElement("div");
    toastEl.className =
      "fixed top-4 right-4 bg-green-600 text-white px-6 py-4 rounded-lg shadow-lg z-50 flex items-center gap-3";
    toastEl.innerHTML = `
      <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
      </svg>
      <span class="font-semibold">발주서가 본사로 전송되었습니다!</span>
    `;
    document.body.appendChild(toastEl);

    setTimeout(() => {
      toastEl.remove();
      navigate("/orders/history");
    }, 2000);
  };

  const totalItems = orderItems.length;
  const totalQuantity = orderItems.reduce(
    (sum, item) => sum + item.requestedQty,
    0
  );

  // 검색 필터링
  const filteredAvailableItems = allAvailableItems.filter((item) => {
    const matchesSearch =
      item.itemName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.itemCode.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.category.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesSearch;
  });

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold text-gray-900">발주서 작성</h2>
          <p className="text-gray-500 mt-1">
            자동 생성된 발주서를 확인하고 품목을 추가하거나 수정하세요
          </p>
        </div>
        <div className="flex gap-3">
          <button
            onClick={handleSaveDraft}
            className="flex items-center gap-2 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors"
          >
            <Save className="w-5 h-5" />
            초안 저장
          </button>
          <button
            onClick={() => setShowSendModal(true)}
            disabled={orderItems.length === 0}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:bg-gray-300 disabled:cursor-not-allowed"
          >
            <Send className="w-5 h-5" />
            본사 전송
          </button>
        </div>
      </div>

      {/* Order Items Table */}
      <div className="space-y-4">
        {/* 안전재고 미달 품목 */}
        {orderItems.filter((item) => item.currentStock < item.safetyStock).length > 0 && (
          <div className="bg-white rounded-lg border-2 border-yellow-300 overflow-hidden">
            <div className="px-6 py-4 bg-yellow-50 border-b-2 border-yellow-300">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-yellow-100 text-yellow-600 flex items-center justify-center">
                    <AlertTriangle className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className="text-lg font-bold text-yellow-900">
                      안전재고 미달 품목
                    </h3>
                    <p className="text-sm text-yellow-700 mt-0.5">
                      {orderItems.filter((item) => item.currentStock < item.safetyStock).length}개 품목이 안전 재고보다 부족합니다
                    </p>
                  </div>
                </div>
                <div className="px-4 py-2 bg-yellow-200 text-yellow-900 rounded-lg font-semibold">
                  {orderItems.filter((item) => item.currentStock < item.safetyStock).length}개
                </div>
              </div>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-yellow-50 border-b border-yellow-200">
                  <tr>
                    <th className="text-left py-3 px-6 text-sm font-semibold text-gray-900">
                      품목코드
                    </th>
                    <th className="text-left py-3 px-6 text-sm font-semibold text-gray-900">
                      품목명
                    </th>
                    <th className="text-left py-3 px-6 text-sm font-semibold text-gray-900">
                      카테고리
                    </th>
                    <th className="text-right py-3 px-6 text-sm font-semibold text-gray-900">
                      현재 재고
                    </th>
                    <th className="text-right py-3 px-6 text-sm font-semibold text-gray-900">
                      안전 재고
                    </th>
                    <th className="text-center py-3 px-6 text-sm font-semibold text-gray-900">
                      요청 수량
                    </th>
                    <th className="text-left py-3 px-6 text-sm font-semibold text-gray-900">
                      사유
                    </th>
                    <th className="text-center py-3 px-6 text-sm font-semibold text-gray-900">
                      작업
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {orderItems
                    .filter((item) => item.currentStock < item.safetyStock)
                    .map((item) => (
                      <tr
                        key={item.id}
                        className="border-b border-gray-100 hover:bg-yellow-50 bg-white"
                      >
                        <td className="py-4 px-6 font-mono text-sm text-gray-600">
                          {item.itemCode}
                        </td>
                        <td className="py-4 px-6 font-medium text-gray-900">
                          {item.itemName}
                        </td>
                        <td className="py-4 px-6">
                          <span className="px-2 py-1 bg-gray-100 text-gray-700 text-xs rounded-full">
                            {item.category}
                          </span>
                        </td>
                        <td className="py-4 px-6 text-right font-semibold text-red-600">
                          {item.currentStock}
                          {item.unit}
                        </td>
                        <td className="py-4 px-6 text-right text-gray-900">
                          {item.safetyStock}
                          {item.unit}
                        </td>
                        <td className="py-4 px-6">
                          <div className="flex items-center justify-center gap-2">
                            <input
                              type="number"
                              value={item.requestedQty}
                              onChange={(e) =>
                                updateQuantity(item.id, Number(e.target.value))
                              }
                              min="1"
                              className="w-24 px-3 py-2 border border-gray-300 rounded-lg text-center font-semibold text-blue-600 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                            />
                            <span className="text-gray-600">{item.unit}</span>
                            <Edit className="w-4 h-4 text-gray-400" />
                          </div>
                        </td>
                        <td className="py-4 px-6">
                          <input
                            type="text"
                            value={item.reason}
                            onChange={(e) => updateReason(item.id, e.target.value)}
                            className="w-full px-2 py-1 border border-gray-300 rounded text-sm text-gray-600 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                            placeholder="발주 사유"
                          />
                        </td>
                        <td className="py-4 px-6 text-center">
                          <button
                            onClick={() => removeItem(item.id)}
                            className="inline-flex items-center gap-1 px-2 py-1 text-red-600 hover:text-red-700 hover:bg-red-50 rounded-lg transition-colors"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </td>
                      </tr>
                    ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* 추가 발주 품목 */}
        {orderItems.filter((item) => item.currentStock >= item.safetyStock).length > 0 && (
          <div className="bg-white rounded-lg border-2 border-blue-300 overflow-hidden">
            <div className="px-6 py-4 bg-blue-50 border-b-2 border-blue-300">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-blue-100 text-blue-600 flex items-center justify-center">
                    <Plus className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className="text-lg font-bold text-blue-900">
                      추가 발주 품목
                    </h3>
                    <p className="text-sm text-blue-700 mt-0.5">
                      수동으로 추가한 발주 품목입니다
                    </p>
                  </div>
                </div>
                <div className="px-4 py-2 bg-blue-200 text-blue-900 rounded-lg font-semibold">
                  {orderItems.filter((item) => item.currentStock >= item.safetyStock).length}개
                </div>
              </div>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-blue-50 border-b border-blue-200">
                  <tr>
                    <th className="text-left py-3 px-6 text-sm font-semibold text-gray-900">
                      품목코드
                    </th>
                    <th className="text-left py-3 px-6 text-sm font-semibold text-gray-900">
                      품목명
                    </th>
                    <th className="text-left py-3 px-6 text-sm font-semibold text-gray-900">
                      카테고리
                    </th>
                    <th className="text-right py-3 px-6 text-sm font-semibold text-gray-900">
                      현재 재고
                    </th>
                    <th className="text-right py-3 px-6 text-sm font-semibold text-gray-900">
                      안전 재고
                    </th>
                    <th className="text-center py-3 px-6 text-sm font-semibold text-gray-900">
                      요청 수량
                    </th>
                    <th className="text-left py-3 px-6 text-sm font-semibold text-gray-900">
                      사유
                    </th>
                    <th className="text-center py-3 px-6 text-sm font-semibold text-gray-900">
                      작업
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {orderItems
                    .filter((item) => item.currentStock >= item.safetyStock)
                    .map((item) => (
                      <tr
                        key={item.id}
                        className="border-b border-gray-100 hover:bg-blue-50 bg-white"
                      >
                        <td className="py-4 px-6 font-mono text-sm text-gray-600">
                          {item.itemCode}
                        </td>
                        <td className="py-4 px-6 font-medium text-gray-900">
                          {item.itemName}
                        </td>
                        <td className="py-4 px-6">
                          <span className="px-2 py-1 bg-gray-100 text-gray-700 text-xs rounded-full">
                            {item.category}
                          </span>
                        </td>
                        <td className="py-4 px-6 text-right font-semibold text-gray-900">
                          {item.currentStock}
                          {item.unit}
                        </td>
                        <td className="py-4 px-6 text-right text-gray-900">
                          {item.safetyStock}
                          {item.unit}
                        </td>
                        <td className="py-4 px-6">
                          <div className="flex items-center justify-center gap-2">
                            <input
                              type="number"
                              value={item.requestedQty}
                              onChange={(e) =>
                                updateQuantity(item.id, Number(e.target.value))
                              }
                              min="1"
                              className="w-24 px-3 py-2 border border-gray-300 rounded-lg text-center font-semibold text-blue-600 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                            />
                            <span className="text-gray-600">{item.unit}</span>
                            <Edit className="w-4 h-4 text-gray-400" />
                          </div>
                        </td>
                        <td className="py-4 px-6">
                          <input
                            type="text"
                            value={item.reason}
                            onChange={(e) => updateReason(item.id, e.target.value)}
                            className="w-full px-2 py-1 border border-gray-300 rounded text-sm text-gray-600 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                            placeholder="발주 사유"
                          />
                        </td>
                        <td className="py-4 px-6 text-center">
                          <button
                            onClick={() => removeItem(item.id)}
                            className="inline-flex items-center gap-1 px-2 py-1 text-red-600 hover:text-red-700 hover:bg-red-50 rounded-lg transition-colors"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </td>
                      </tr>
                    ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* 품목이 없을 때 */}
        {orderItems.length === 0 && (
          <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">
            <div className="px-6 py-4 border-b border-gray-200 bg-gray-50 flex items-center justify-between">
              <div>
                <h3 className="font-semibold text-lg text-gray-900">
                  발주 품목 리스트
                </h3>
                <p className="text-sm text-gray-500 mt-1">
                  수량을 수정하거나 품목을 추가/삭제할 수 있습니다
                </p>
              </div>
              <button
                onClick={() => setShowAddItemModal(true)}
                className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
              >
                <Plus className="w-5 h-5" />
                품목 추가
              </button>
            </div>
            <div className="py-12 text-center">
              <FileText className="w-16 h-16 text-gray-300 mx-auto mb-4" />
              <p className="text-gray-500 text-lg mb-2">발주 품목이 없습니다</p>
              <p className="text-gray-400 text-sm mb-4">
                품목 추가 버튼을 클릭하여 발주할 품목을 추가하세요
              </p>
              <button
                onClick={() => setShowAddItemModal(true)}
                className="inline-flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
              >
                <Plus className="w-5 h-5" />
                품목 추가
              </button>
            </div>
          </div>
        )}

        {/* 품목 추가 버튼 (품목이 있을 때) */}
        {orderItems.length > 0 && (
          <div className="flex justify-center">
            <button
              onClick={() => setShowAddItemModal(true)}
              className="flex items-center gap-2 px-6 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors shadow-md"
            >
              <Plus className="w-5 h-5" />
              품목 추가
            </button>
          </div>
        )}
      </div>

      {/* Add Item Modal */}
      {showAddItemModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-lg max-w-4xl w-full max-h-[80vh] overflow-hidden flex flex-col">
            <div className="px-6 py-4 border-b border-gray-200">
              <div className="flex items-center justify-between mb-4">
                <div>
                  <h3 className="text-xl font-bold text-gray-900">
                    발주 품목 추가
                  </h3>
                  <p className="text-sm text-gray-500 mt-1">
                    발주할 품목을 선택하세요
                  </p>
                </div>
                <button
                  onClick={() => {
                    setShowAddItemModal(false);
                    setSearchTerm("");
                  }}
                  className="text-gray-400 hover:text-gray-600"
                >
                  <span className="sr-only">닫기</span>
                  ✕
                </button>
              </div>

              {/* Search */}
              <div className="relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  type="text"
                  placeholder="품목명, 품목코드, 카테고리로 검색..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>
            </div>

            <div className="flex-1 overflow-y-auto p-6">
              <div className="grid grid-cols-1 gap-3">
                {filteredAvailableItems.map((item) => {
                  const isAdded = orderItems.some(
                    (oi) => oi.itemCode === item.itemCode
                  );
                  const isLowStock = item.currentStock < item.safetyStock;

                  return (
                    <div
                      key={item.itemCode}
                      className={`border rounded-lg p-4 ${
                        isLowStock
                          ? "border-yellow-300 bg-yellow-50"
                          : "border-gray-200 bg-white"
                      } ${isAdded ? "opacity-50" : ""}`}
                    >
                      <div className="flex items-center justify-between">
                        <div className="flex-1">
                          <div className="flex items-center gap-3">
                            <h4 className="font-semibold text-gray-900">
                              {item.itemName}
                            </h4>
                            <span className="px-2 py-1 bg-gray-100 text-gray-700 text-xs rounded-full">
                              {item.category}
                            </span>
                            {isLowStock && (
                              <span className="inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium bg-yellow-100 text-yellow-700">
                                <AlertTriangle className="w-3 h-3" />
                                재고 부족
                              </span>
                            )}
                          </div>
                          <p className="text-sm text-gray-500 mt-1">
                            품목코드: {item.itemCode}
                          </p>
                          <div className="flex items-center gap-4 mt-2 text-sm">
                            <span
                              className={`font-semibold ${
                                isLowStock ? "text-red-600" : "text-gray-900"
                              }`}
                            >
                              현재: {item.currentStock}
                              {item.unit}
                            </span>
                            <span className="text-gray-600">
                              안전: {item.safetyStock}
                              {item.unit}
                            </span>
                            {isLowStock && (
                              <span className="text-red-600 font-semibold">
                                부족: {item.safetyStock - item.currentStock}
                                {item.unit}
                              </span>
                            )}
                          </div>
                        </div>
                        <button
                          onClick={() => addItem(item)}
                          disabled={isAdded}
                          className={`ml-4 px-4 py-2 rounded-lg transition-colors ${
                            isAdded
                              ? "bg-gray-200 text-gray-500 cursor-not-allowed"
                              : "bg-green-600 text-white hover:bg-green-700"
                          }`}
                        >
                          {isAdded ? "추가됨" : "추가"}
                        </button>
                      </div>
                    </div>
                  );
                })}

                {filteredAvailableItems.length === 0 && (
                  <div className="text-center py-12">
                    <Search className="w-16 h-16 text-gray-300 mx-auto mb-4" />
                    <p className="text-gray-500">검색 결과가 없습니다</p>
                  </div>
                )}
              </div>
            </div>

            <div className="px-6 py-4 border-t border-gray-200 bg-gray-50">
              <button
                onClick={() => {
                  setShowAddItemModal(false);
                  setSearchTerm("");
                }}
                className="w-full px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-100 transition-colors"
              >
                닫기
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Send Confirmation Modal */}
      {showSendModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-lg max-w-md w-full p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-12 h-12 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center">
                <Send className="w-6 h-6" />
              </div>
              <div>
                <h3 className="text-lg font-bold text-gray-900">
                  발주서 전송 확인
                </h3>
                <p className="text-sm text-gray-500">본사로 발주서를 전송합니다</p>
              </div>
            </div>

            <div className="bg-blue-50 rounded-lg p-4 mb-4 border border-blue-200">
              <div className="space-y-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-blue-700">발주 품목 수</span>
                  <span className="font-semibold text-blue-900">
                    {totalItems}개
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-blue-700">총 요청 수량</span>
                  <span className="font-semibold text-blue-900">
                    {totalQuantity}개 단위
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-blue-700">재고 부족 품목</span>
                  <span className="font-semibold text-red-600">
                    {
                      orderItems.filter(
                        (i) => i.currentStock < i.safetyStock
                      ).length
                    }
                    개
                  </span>
                </div>
              </div>
            </div>

            <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-3 mb-4">
              <p className="text-xs text-yellow-800">
                <strong>안내:</strong> 전송 후 본사의 승인을 기다려야 합니다.
                반려된 경우 수정 후 재전송이 가능합니다.
              </p>
            </div>

            <div className="flex gap-3">
              <button
                onClick={() => setShowSendModal(false)}
                className="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors"
              >
                취소
              </button>
              <button
                onClick={handleSend}
                className="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
              >
                전송
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
